name: Code Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'v2rayN/ServiceLib/**'
      - 'v2rayN/ServiceLib.Tests/**'
      - 'v2rayN/AmazTool/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Test Code
      working-directory: ./v2rayN
      run: dotnet test ./ServiceLib.Tests
